### ISSUE TITLE
Listening ipv6 app mistakenly marked as CLOSE

### ISSUE THREAD

**Issue by haarp** [eolwral/OSMonitor#51] opened 2014-12-28 10:08 UTC
I have an app that listens on an UDP6 port. It looks like this:

UDP6
127.0.0.1:45658
:::*

The connection monitor however marks it as CLOSE instead of LISTEN

**Comment by eolwral** [comment] 2015-02-07 08:06
It seems a common mistake, if you run "nestat -na" on Android emulator, you will see same result, the problem is UDP status set as 0x7, which is CLOSE on TCP status, I have checked out the source code of Linux, unfortunately there isn't exist anything about UDP status, after digging the source code of busybox I discover UDP shouldn't have a status expect "ESTABLISHED", it looks like below link. 

https://gitorious.org/busybox/busybox/source/1c7a58dfb82ea04c525e0c19f94f2d800dee99e3:networking/netstat.c#L480-503

I decide to mark 0x7 as LISTEN on UDP, it looks more reasonable.  :)

**Comment by eolwral** [comment] 2015-02-07 08:09
I have committed this patch. 475e31d8c4b2fa805cab816022a464ae2e9f5f7c

**Comment by haarp** [comment] 2015-02-07 08:56
Interesting explanation, thanks! :)

**Comment by eolwral** [comment] 2015-02-07 19:35
The patched version has been pushed, it should available a few hours later. :)

Close ticket.

**Closed by eolwral** 2015-02-07 19:35 UTC
